/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const Time = IDL.Int;
export const AlarmConfig = IDL.Record({
  'alertBeep' : IDL.Text,
  'ringTone' : IDL.Text,
  'alarmId' : IDL.Text,
  'userId' : IDL.Principal,
  'createdAt' : Time,
  'wakeUpTime' : Time,
  'isActive' : IDL.Bool,
  'language' : IDL.Text,
  'updatedAt' : Time,
});
export const CaseStudy = IDL.Record({
  'id' : IDL.Text,
  'region' : IDL.Text,
  'protocolsUsed' : IDL.Vec(IDL.Text),
  'title' : IDL.Text,
  'createdAt' : Time,
  'description' : IDL.Text,
  'reliability' : IDL.Float64,
  'updatedAt' : Time,
  'energySavings' : IDL.Float64,
});
export const DNSSyncResult = IDL.Record({
  'domain' : IDL.Text,
  'message' : IDL.Text,
  'timestamp' : Time,
  'success' : IDL.Bool,
});
export const DeviceQuality = IDL.Variant({
  'bad' : IDL.Null,
  'good' : IDL.Null,
  'uncertain' : IDL.Null,
});
export const DiagnosticCheckResult = IDL.Record({
  'status' : IDL.Text,
  'message' : IDL.Text,
  'checkType' : IDL.Text,
  'timestamp' : Time,
});
export const DiagnosticEvent = IDL.Record({
  'id' : IDL.Text,
  'status' : IDL.Text,
  'tagId' : IDL.Text,
  'manufacturerReferralUrl' : IDL.Opt(IDL.Text),
  'userId' : IDL.Principal,
  'quality' : DeviceQuality,
  'errorCode' : IDL.Opt(IDL.Text),
  'diagnosis' : IDL.Text,
  'progressPercent' : IDL.Nat,
  'deviceId' : IDL.Text,
  'timestamp' : Time,
  'suggestedActions' : IDL.Vec(IDL.Text),
  'checks' : IDL.Vec(DiagnosticCheckResult),
});
export const DiagnosticFeedback = IDL.Record({
  'id' : IDL.Text,
  'userId' : IDL.Principal,
  'comment' : IDL.Opt(IDL.Text),
  'wasHelpful' : IDL.Bool,
  'diagnosticEventId' : IDL.Text,
  'timestamp' : Time,
});
export const EVProvider = IDL.Variant({
  'ford' : IDL.Null,
  'rivian' : IDL.Null,
});
export const EVOAuthConfig = IDL.Record({
  'expiresAt' : Time,
  'provider' : EVProvider,
  'refreshToken' : IDL.Text,
  'userId' : IDL.Principal,
  'createdAt' : Time,
  'updatedAt' : Time,
  'accessToken' : IDL.Text,
});
export const EVTelemetry = IDL.Record({
  'provider' : EVProvider,
  'batteryPercent' : IDL.Float64,
  'userId' : IDL.Principal,
  'chargingStatus' : IDL.Text,
  'timestamp' : Time,
  'rangeKm' : IDL.Float64,
  'vehicleId' : IDL.Text,
});
export const EnergyData = IDL.Record({
  'temperature' : IDL.Float64,
  'systemId' : IDL.Text,
  'timestamp' : Time,
  'energyConsumption' : IDL.Float64,
  'location' : IDL.Text,
  'timeZone' : IDL.Text,
});
export const EnergySummary = IDL.Record({
  'totalConsumption' : IDL.Float64,
  'systemId' : IDL.Text,
  'peakUsage' : IDL.Float64,
  'timestamp' : Time,
});
export const ErrorCode = IDL.Record({
  'manufacturer' : IDL.Text,
  'code' : IDL.Text,
  'createdAt' : Time,
  'supportUrl' : IDL.Text,
  'description' : IDL.Text,
  'isActive' : IDL.Bool,
  'updatedAt' : Time,
  'plainEnglishMessage' : IDL.Text,
});
export const ICPGatewayConfig = IDL.Record({
  'domain' : IDL.Text,
  'errorMessage' : IDL.Opt(IDL.Text),
  'tlsCertificateValid' : IDL.Bool,
  'lastSyncTimestamp' : Time,
  'isRegistered' : IDL.Bool,
  'canisterId' : IDL.Text,
});
export const LearningUpdate = IDL.Record({
  'id' : IDL.Text,
  'impact' : IDL.Text,
  'issuePattern' : IDL.Text,
  'deviceCorrelation' : IDL.Text,
  'timestamp' : Time,
  'optimizationSuggestion' : IDL.Text,
});
export const MaintenanceEvent = IDL.Record({
  'id' : IDL.Text,
  'service' : IDL.Text,
  'status' : IDL.Text,
  'issueType' : IDL.Text,
  'resolution' : IDL.Text,
  'retryCount' : IDL.Nat,
  'timeToResolution' : IDL.Int,
  'timestamp' : Time,
  'rootCause' : IDL.Text,
});
export const ManufacturerSupport = IDL.Record({
  'id' : IDL.Text,
  'name' : IDL.Text,
  'createdAt' : Time,
  'supportUrl' : IDL.Text,
  'description' : IDL.Text,
  'isActive' : IDL.Bool,
  'updatedAt' : Time,
  'logoUrl' : IDL.Text,
});
export const MotivationalMessage = IDL.Record({
  'content' : IDL.Text,
  'messageId' : IDL.Text,
  'language' : IDL.Text,
  'timestamp' : Time,
});
export const PredictiveModel = IDL.Record({
  'lastUpdated' : Time,
  'systemId' : IDL.Text,
  'modelData' : IDL.Text,
  'modelId' : IDL.Text,
  'timeZone' : IDL.Text,
});
export const PricingTier = IDL.Record({
  'id' : IDL.Text,
  'features' : IDL.Vec(IDL.Text),
  'tierType' : IDL.Text,
  'name' : IDL.Text,
  'createdAt' : Time,
  'description' : IDL.Text,
  'isActive' : IDL.Bool,
  'updatedAt' : Time,
  'currency' : IDL.Text,
  'price' : IDL.Float64,
});
export const Recommendation = IDL.Record({
  'id' : IDL.Text,
  'region' : IDL.Text,
  'systemId' : IDL.Text,
  'language' : IDL.Text,
  'message' : IDL.Text,
  'timestamp' : Time,
});
export const RegionalPricingModel = IDL.Record({
  'region' : IDL.Text,
  'peakHours' : IDL.Vec(IDL.Text),
  'pricePerKWh' : IDL.Float64,
  'currency' : IDL.Text,
});
export const ScadaProtocolSupport = IDL.Record({
  'id' : IDL.Text,
  'protocol' : IDL.Text,
  'createdAt' : Time,
  'tier' : IDL.Text,
  'description' : IDL.Text,
  'isActive' : IDL.Bool,
  'supportedDevices' : IDL.Vec(IDL.Text),
  'updatedAt' : Time,
});
export const ScheduledUpdate = IDL.Record({
  'updateType' : IDL.Text,
  'userId' : IDL.Principal,
  'createdAt' : Time,
  'isActive' : IDL.Bool,
  'updateId' : IDL.Text,
  'updatedAt' : Time,
  'scheduleTime' : Time,
  'frequency' : IDL.Text,
});
export const SupportBoundary = IDL.Record({
  'id' : IDL.Text,
  'createdAt' : Time,
  'description' : IDL.Text,
  'isActive' : IDL.Bool,
  'updatedAt' : Time,
});
export const SupportContract = IDL.Record({
  'expiresAt' : Time,
  'userId' : IDL.Principal,
  'tier' : IDL.Text,
  'isActive' : IDL.Bool,
});
export const SupportedDevice = IDL.Record({
  'region' : IDL.Text,
  'model' : IDL.Text,
  'brand' : IDL.Text,
  'systemType' : IDL.Text,
});
export const SystemConfig = IDL.Record({
  'region' : IDL.Text,
  'authToken' : IDL.Text,
  'owner' : IDL.Principal,
  'systemId' : IDL.Text,
  'apiEndpoint' : IDL.Text,
  'brand' : IDL.Text,
  'systemType' : IDL.Text,
});
export const ValueProposition = IDL.Record({
  'id' : IDL.Text,
  'title' : IDL.Text,
  'createdAt' : Time,
  'description' : IDL.Text,
  'targetAudience' : IDL.Text,
  'updatedAt' : Time,
  'benefits' : IDL.Vec(IDL.Text),
});
export const WeatherData = IDL.Record({
  'temperature' : IDL.Float64,
  'timestamp' : Time,
  'location' : IDL.Text,
  'condition' : IDL.Text,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const ShoppingItem = IDL.Record({
  'productName' : IDL.Text,
  'currency' : IDL.Text,
  'quantity' : IDL.Nat,
  'priceInCents' : IDL.Nat,
  'productDescription' : IDL.Text,
});
export const DeviceHealth = IDL.Record({
  'tagId' : IDL.Text,
  'userId' : IDL.Principal,
  'quality' : DeviceQuality,
  'lastValue' : IDL.Opt(IDL.Text),
  'deviceId' : IDL.Text,
  'lastChecked' : Time,
  'lastValueTimestamp' : Time,
});
export const SystemConfigPublic = IDL.Record({
  'region' : IDL.Text,
  'systemId' : IDL.Text,
  'apiEndpoint' : IDL.Text,
  'brand' : IDL.Text,
  'systemType' : IDL.Text,
});
export const UserProfile = IDL.Record({
  'preferredLanguage' : IDL.Text,
  'name' : IDL.Text,
});
export const NercCipStandard = IDL.Record({
  'title' : IDL.Text,
  'description' : IDL.Text,
  'standardId' : IDL.Text,
  'purpose' : IDL.Text,
});
export const ComplianceSubsection = IDL.Record({
  'title' : IDL.Text,
  'content' : IDL.Text,
});
export const ComplianceSection = IDL.Record({
  'title' : IDL.Text,
  'content' : IDL.Text,
  'subsections' : IDL.Vec(ComplianceSubsection),
});
export const ComplianceReportData = IDL.Record({
  'title' : IDL.Text,
  'quickReferenceTable' : IDL.Text,
  'nercCipStandards' : IDL.Vec(NercCipStandard),
  'generatedAt' : Time,
  'legalDeclaration' : IDL.Text,
  'sections' : IDL.Vec(ComplianceSection),
  'nistCsfResponsibilities' : IDL.Text,
});
export const CanisterStatus = IDL.Variant({
  'failing' : IDL.Null,
  'offline' : IDL.Null,
  'unknown' : IDL.Null,
  'online' : IDL.Null,
});
export const CanisterInfo = IDL.Record({
  'status' : CanisterStatus,
  'name' : IDL.Text,
  'errorMessage' : IDL.Opt(IDL.Text),
  'lastChecked' : Time,
  'canisterId' : IDL.Text,
});
export const DomainStatus = IDL.Record({
  'isAccessible' : IDL.Bool,
  'sslValid' : IDL.Bool,
  'lastChecked' : Time,
  'primaryDomain' : IDL.Text,
});
export const DeploymentStatus = IDL.Record({
  'canisters' : IDL.Vec(CanisterInfo),
  'timestamp' : Time,
  'overallStatus' : IDL.Text,
  'domainStatus' : DomainStatus,
});
export const DomainVariant = IDL.Record({
  'domain' : IDL.Text,
  'isAvailable' : IDL.Bool,
  'registrar' : IDL.Text,
  'lastChecked' : Time,
  'priceUsd' : IDL.Float64,
});
export const DomainPortfolio = IDL.Record({
  'recommendations' : IDL.Text,
  'strategy' : IDL.Text,
  'lastUpdated' : Time,
  'variants' : IDL.Vec(DomainVariant),
});
export const MaintenanceConfig = IDL.Record({
  'alertEscalationThreshold' : IDL.Nat,
  'createdAt' : Time,
  'autoRepairThreshold' : IDL.Nat,
  'maxRetries' : IDL.Nat,
  'isActive' : IDL.Bool,
  'updatedAt' : Time,
});
export const ServiceStatus = IDL.Variant({
  'unhealthy' : IDL.Null,
  'healthy' : IDL.Null,
  'degraded' : IDL.Null,
  'unknown' : IDL.Null,
});
export const SystemHealth = IDL.Record({
  'activeProcesses' : IDL.Vec(IDL.Text),
  'dataSyncStatus' : ServiceStatus,
  'deviceIntegrationStatus' : ServiceStatus,
  'backendStatus' : ServiceStatus,
  'networkStatus' : ServiceStatus,
  'uptime' : IDL.Float64,
  'performanceMetrics' : IDL.Text,
  'overallStatus' : ServiceStatus,
});
export const MaintenanceDashboard = IDL.Record({
  'optimizationSuggestions' : IDL.Vec(IDL.Text),
  'learningUpdates' : IDL.Vec(LearningUpdate),
  'config' : MaintenanceConfig,
  'systemHealth' : SystemHealth,
  'recentEvents' : IDL.Vec(MaintenanceEvent),
});
export const StripeSessionStatus = IDL.Variant({
  'completed' : IDL.Record({
    'userPrincipal' : IDL.Opt(IDL.Text),
    'response' : IDL.Text,
  }),
  'failed' : IDL.Record({ 'error' : IDL.Text }),
});
export const StripeConfiguration = IDL.Record({
  'allowedCountries' : IDL.Vec(IDL.Text),
  'secretKey' : IDL.Text,
});
export const http_header = IDL.Record({
  'value' : IDL.Text,
  'name' : IDL.Text,
});
export const http_request_result = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});
export const TransformationInput = IDL.Record({
  'context' : IDL.Vec(IDL.Nat8),
  'response' : http_request_result,
});
export const TransformationOutput = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  'addAlarmConfig' : IDL.Func([AlarmConfig], [], []),
  'addCaseStudy' : IDL.Func([CaseStudy], [], []),
  'addDNSSyncResult' : IDL.Func([DNSSyncResult], [], []),
  'addDiagnosticEvent' : IDL.Func([DiagnosticEvent], [], []),
  'addDiagnosticFeedback' : IDL.Func([DiagnosticFeedback], [], []),
  'addEVOAuthConfig' : IDL.Func([EVOAuthConfig], [], []),
  'addEVTelemetry' : IDL.Func([EVTelemetry], [], []),
  'addEnergyData' : IDL.Func([EnergyData], [], []),
  'addEnergySummary' : IDL.Func([EnergySummary], [], []),
  'addErrorCode' : IDL.Func([ErrorCode], [], []),
  'addICPGatewayConfig' : IDL.Func([ICPGatewayConfig], [], []),
  'addLearningUpdate' : IDL.Func([LearningUpdate], [], []),
  'addMaintenanceEvent' : IDL.Func([MaintenanceEvent], [], []),
  'addManufacturerSupport' : IDL.Func([ManufacturerSupport], [], []),
  'addMotivationalMessage' : IDL.Func([MotivationalMessage], [], []),
  'addPredictiveModel' : IDL.Func([PredictiveModel], [], []),
  'addPricingTier' : IDL.Func([PricingTier], [], []),
  'addRecommendation' : IDL.Func([Recommendation], [], []),
  'addRegionalPricingModel' : IDL.Func([RegionalPricingModel], [], []),
  'addScadaProtocol' : IDL.Func([ScadaProtocolSupport], [], []),
  'addScheduledUpdate' : IDL.Func([ScheduledUpdate], [], []),
  'addSupportBoundary' : IDL.Func([SupportBoundary], [], []),
  'addSupportContract' : IDL.Func([SupportContract], [], []),
  'addSupportedDevice' : IDL.Func([SupportedDevice], [], []),
  'addSystemConfig' : IDL.Func([SystemConfig], [], []),
  'addValueProposition' : IDL.Func([ValueProposition], [], []),
  'addWeatherData' : IDL.Func([WeatherData], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createCheckoutSession' : IDL.Func(
      [IDL.Vec(ShoppingItem), IDL.Text, IDL.Text],
      [IDL.Text],
      [],
    ),
  'deleteAlarmConfig' : IDL.Func([IDL.Text], [], []),
  'deleteEnergyData' : IDL.Func([IDL.Text, Time], [], []),
  'deletePredictiveModel' : IDL.Func([IDL.Text], [], []),
  'deleteRecommendation' : IDL.Func([IDL.Text], [], []),
  'deleteRegionalPricingModel' : IDL.Func([IDL.Text], [], []),
  'deleteScheduledUpdate' : IDL.Func([IDL.Text], [], []),
  'deleteSupportedDevice' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'deleteSystemConfig' : IDL.Func([IDL.Text], [], []),
  'getAlarmConfig' : IDL.Func([IDL.Text], [IDL.Opt(AlarmConfig)], ['query']),
  'getAllAlarmConfigs' : IDL.Func([], [IDL.Vec(AlarmConfig)], ['query']),
  'getAllCaseStudies' : IDL.Func([], [IDL.Vec(CaseStudy)], ['query']),
  'getAllDeviceHealth' : IDL.Func([], [IDL.Vec(DeviceHealth)], ['query']),
  'getAllDiagnosticEvents' : IDL.Func(
      [],
      [IDL.Vec(DiagnosticEvent)],
      ['query'],
    ),
  'getAllEnergyData' : IDL.Func([], [IDL.Vec(EnergyData)], ['query']),
  'getAllErrorCodes' : IDL.Func([], [IDL.Vec(ErrorCode)], ['query']),
  'getAllICPGatewayConfigs' : IDL.Func(
      [],
      [IDL.Vec(ICPGatewayConfig)],
      ['query'],
    ),
  'getAllManufacturerSupport' : IDL.Func(
      [],
      [IDL.Vec(ManufacturerSupport)],
      ['query'],
    ),
  'getAllMotivationalMessages' : IDL.Func(
      [],
      [IDL.Vec(MotivationalMessage)],
      ['query'],
    ),
  'getAllPricingTiers' : IDL.Func([], [IDL.Vec(PricingTier)], ['query']),
  'getAllRegionalPricingModels' : IDL.Func(
      [],
      [IDL.Vec(RegionalPricingModel)],
      ['query'],
    ),
  'getAllScadaProtocols' : IDL.Func(
      [],
      [IDL.Vec(ScadaProtocolSupport)],
      ['query'],
    ),
  'getAllScheduledUpdates' : IDL.Func(
      [],
      [IDL.Vec(ScheduledUpdate)],
      ['query'],
    ),
  'getAllSupportBoundaries' : IDL.Func(
      [],
      [IDL.Vec(SupportBoundary)],
      ['query'],
    ),
  'getAllSupportedDevices' : IDL.Func(
      [],
      [IDL.Vec(SupportedDevice)],
      ['query'],
    ),
  'getAllSystemConfigs' : IDL.Func(
      [],
      [IDL.Vec(SystemConfigPublic)],
      ['query'],
    ),
  'getAllSystemConfigsFull' : IDL.Func([], [IDL.Vec(SystemConfig)], ['query']),
  'getAllValuePropositions' : IDL.Func(
      [],
      [IDL.Vec(ValueProposition)],
      ['query'],
    ),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getComplianceReportData' : IDL.Func(
      [],
      [IDL.Opt(ComplianceReportData)],
      ['query'],
    ),
  'getDNSSyncHistory' : IDL.Func([], [IDL.Vec(DNSSyncResult)], ['query']),
  'getDeploymentStatus' : IDL.Func([], [IDL.Opt(DeploymentStatus)], ['query']),
  'getDeviceHealth' : IDL.Func([IDL.Text], [IDL.Opt(DeviceHealth)], ['query']),
  'getDiagnosticEvent' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(DiagnosticEvent)],
      ['query'],
    ),
  'getDiagnosticFeedback' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(DiagnosticFeedback)],
      ['query'],
    ),
  'getDomainPortfolio' : IDL.Func([], [IDL.Opt(DomainPortfolio)], ['query']),
  'getEVOAuthConfig' : IDL.Func(
      [IDL.Principal, EVProvider],
      [IDL.Opt(EVOAuthConfig)],
      ['query'],
    ),
  'getEVTelemetry' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(EVTelemetry)],
      ['query'],
    ),
  'getEnergyData' : IDL.Func([IDL.Text], [IDL.Vec(EnergyData)], ['query']),
  'getEnergySummary' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(EnergySummary)],
      ['query'],
    ),
  'getErrorCode' : IDL.Func(
      [IDL.Text, IDL.Text],
      [IDL.Opt(ErrorCode)],
      ['query'],
    ),
  'getMaintenanceDashboard' : IDL.Func([], [MaintenanceDashboard], ['query']),
  'getPredictiveModel' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(PredictiveModel)],
      ['query'],
    ),
  'getRecommendations' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(Recommendation)],
      ['query'],
    ),
  'getRegionalPricingModel' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(RegionalPricingModel)],
      ['query'],
    ),
  'getScheduledUpdate' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(ScheduledUpdate)],
      ['query'],
    ),
  'getStripeSessionStatus' : IDL.Func([IDL.Text], [StripeSessionStatus], []),
  'getSupportContract' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(SupportContract)],
      ['query'],
    ),
  'getSystemConfig' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(SystemConfigPublic)],
      ['query'],
    ),
  'getSystemConfigFull' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(SystemConfig)],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getWeatherData' : IDL.Func([IDL.Text], [IDL.Opt(WeatherData)], ['query']),
  'initializeAccessControl' : IDL.Func([], [], []),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isStripeConfigured' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'setComplianceReportData' : IDL.Func([ComplianceReportData], [], []),
  'setDeploymentStatus' : IDL.Func([DeploymentStatus], [], []),
  'setDomainPortfolio' : IDL.Func([DomainPortfolio], [], []),
  'setStripeConfiguration' : IDL.Func([StripeConfiguration], [], []),
  'transform' : IDL.Func(
      [TransformationInput],
      [TransformationOutput],
      ['query'],
    ),
  'updateAlarmConfig' : IDL.Func([AlarmConfig], [], []),
  'updateDeviceHealth' : IDL.Func([DeviceHealth], [], []),
  'updateMaintenanceConfig' : IDL.Func([MaintenanceConfig], [], []),
  'updatePricingTier' : IDL.Func([PricingTier], [], []),
  'updateSystemConfig' : IDL.Func([SystemConfig], [], []),
  'updateSystemHealth' : IDL.Func([SystemHealth], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const Time = IDL.Int;
  const AlarmConfig = IDL.Record({
    'alertBeep' : IDL.Text,
    'ringTone' : IDL.Text,
    'alarmId' : IDL.Text,
    'userId' : IDL.Principal,
    'createdAt' : Time,
    'wakeUpTime' : Time,
    'isActive' : IDL.Bool,
    'language' : IDL.Text,
    'updatedAt' : Time,
  });
  const CaseStudy = IDL.Record({
    'id' : IDL.Text,
    'region' : IDL.Text,
    'protocolsUsed' : IDL.Vec(IDL.Text),
    'title' : IDL.Text,
    'createdAt' : Time,
    'description' : IDL.Text,
    'reliability' : IDL.Float64,
    'updatedAt' : Time,
    'energySavings' : IDL.Float64,
  });
  const DNSSyncResult = IDL.Record({
    'domain' : IDL.Text,
    'message' : IDL.Text,
    'timestamp' : Time,
    'success' : IDL.Bool,
  });
  const DeviceQuality = IDL.Variant({
    'bad' : IDL.Null,
    'good' : IDL.Null,
    'uncertain' : IDL.Null,
  });
  const DiagnosticCheckResult = IDL.Record({
    'status' : IDL.Text,
    'message' : IDL.Text,
    'checkType' : IDL.Text,
    'timestamp' : Time,
  });
  const DiagnosticEvent = IDL.Record({
    'id' : IDL.Text,
    'status' : IDL.Text,
    'tagId' : IDL.Text,
    'manufacturerReferralUrl' : IDL.Opt(IDL.Text),
    'userId' : IDL.Principal,
    'quality' : DeviceQuality,
    'errorCode' : IDL.Opt(IDL.Text),
    'diagnosis' : IDL.Text,
    'progressPercent' : IDL.Nat,
    'deviceId' : IDL.Text,
    'timestamp' : Time,
    'suggestedActions' : IDL.Vec(IDL.Text),
    'checks' : IDL.Vec(DiagnosticCheckResult),
  });
  const DiagnosticFeedback = IDL.Record({
    'id' : IDL.Text,
    'userId' : IDL.Principal,
    'comment' : IDL.Opt(IDL.Text),
    'wasHelpful' : IDL.Bool,
    'diagnosticEventId' : IDL.Text,
    'timestamp' : Time,
  });
  const EVProvider = IDL.Variant({ 'ford' : IDL.Null, 'rivian' : IDL.Null });
  const EVOAuthConfig = IDL.Record({
    'expiresAt' : Time,
    'provider' : EVProvider,
    'refreshToken' : IDL.Text,
    'userId' : IDL.Principal,
    'createdAt' : Time,
    'updatedAt' : Time,
    'accessToken' : IDL.Text,
  });
  const EVTelemetry = IDL.Record({
    'provider' : EVProvider,
    'batteryPercent' : IDL.Float64,
    'userId' : IDL.Principal,
    'chargingStatus' : IDL.Text,
    'timestamp' : Time,
    'rangeKm' : IDL.Float64,
    'vehicleId' : IDL.Text,
  });
  const EnergyData = IDL.Record({
    'temperature' : IDL.Float64,
    'systemId' : IDL.Text,
    'timestamp' : Time,
    'energyConsumption' : IDL.Float64,
    'location' : IDL.Text,
    'timeZone' : IDL.Text,
  });
  const EnergySummary = IDL.Record({
    'totalConsumption' : IDL.Float64,
    'systemId' : IDL.Text,
    'peakUsage' : IDL.Float64,
    'timestamp' : Time,
  });
  const ErrorCode = IDL.Record({
    'manufacturer' : IDL.Text,
    'code' : IDL.Text,
    'createdAt' : Time,
    'supportUrl' : IDL.Text,
    'description' : IDL.Text,
    'isActive' : IDL.Bool,
    'updatedAt' : Time,
    'plainEnglishMessage' : IDL.Text,
  });
  const ICPGatewayConfig = IDL.Record({
    'domain' : IDL.Text,
    'errorMessage' : IDL.Opt(IDL.Text),
    'tlsCertificateValid' : IDL.Bool,
    'lastSyncTimestamp' : Time,
    'isRegistered' : IDL.Bool,
    'canisterId' : IDL.Text,
  });
  const LearningUpdate = IDL.Record({
    'id' : IDL.Text,
    'impact' : IDL.Text,
    'issuePattern' : IDL.Text,
    'deviceCorrelation' : IDL.Text,
    'timestamp' : Time,
    'optimizationSuggestion' : IDL.Text,
  });
  const MaintenanceEvent = IDL.Record({
    'id' : IDL.Text,
    'service' : IDL.Text,
    'status' : IDL.Text,
    'issueType' : IDL.Text,
    'resolution' : IDL.Text,
    'retryCount' : IDL.Nat,
    'timeToResolution' : IDL.Int,
    'timestamp' : Time,
    'rootCause' : IDL.Text,
  });
  const ManufacturerSupport = IDL.Record({
    'id' : IDL.Text,
    'name' : IDL.Text,
    'createdAt' : Time,
    'supportUrl' : IDL.Text,
    'description' : IDL.Text,
    'isActive' : IDL.Bool,
    'updatedAt' : Time,
    'logoUrl' : IDL.Text,
  });
  const MotivationalMessage = IDL.Record({
    'content' : IDL.Text,
    'messageId' : IDL.Text,
    'language' : IDL.Text,
    'timestamp' : Time,
  });
  const PredictiveModel = IDL.Record({
    'lastUpdated' : Time,
    'systemId' : IDL.Text,
    'modelData' : IDL.Text,
    'modelId' : IDL.Text,
    'timeZone' : IDL.Text,
  });
  const PricingTier = IDL.Record({
    'id' : IDL.Text,
    'features' : IDL.Vec(IDL.Text),
    'tierType' : IDL.Text,
    'name' : IDL.Text,
    'createdAt' : Time,
    'description' : IDL.Text,
    'isActive' : IDL.Bool,
    'updatedAt' : Time,
    'currency' : IDL.Text,
    'price' : IDL.Float64,
  });
  const Recommendation = IDL.Record({
    'id' : IDL.Text,
    'region' : IDL.Text,
    'systemId' : IDL.Text,
    'language' : IDL.Text,
    'message' : IDL.Text,
    'timestamp' : Time,
  });
  const RegionalPricingModel = IDL.Record({
    'region' : IDL.Text,
    'peakHours' : IDL.Vec(IDL.Text),
    'pricePerKWh' : IDL.Float64,
    'currency' : IDL.Text,
  });
  const ScadaProtocolSupport = IDL.Record({
    'id' : IDL.Text,
    'protocol' : IDL.Text,
    'createdAt' : Time,
    'tier' : IDL.Text,
    'description' : IDL.Text,
    'isActive' : IDL.Bool,
    'supportedDevices' : IDL.Vec(IDL.Text),
    'updatedAt' : Time,
  });
  const ScheduledUpdate = IDL.Record({
    'updateType' : IDL.Text,
    'userId' : IDL.Principal,
    'createdAt' : Time,
    'isActive' : IDL.Bool,
    'updateId' : IDL.Text,
    'updatedAt' : Time,
    'scheduleTime' : Time,
    'frequency' : IDL.Text,
  });
  const SupportBoundary = IDL.Record({
    'id' : IDL.Text,
    'createdAt' : Time,
    'description' : IDL.Text,
    'isActive' : IDL.Bool,
    'updatedAt' : Time,
  });
  const SupportContract = IDL.Record({
    'expiresAt' : Time,
    'userId' : IDL.Principal,
    'tier' : IDL.Text,
    'isActive' : IDL.Bool,
  });
  const SupportedDevice = IDL.Record({
    'region' : IDL.Text,
    'model' : IDL.Text,
    'brand' : IDL.Text,
    'systemType' : IDL.Text,
  });
  const SystemConfig = IDL.Record({
    'region' : IDL.Text,
    'authToken' : IDL.Text,
    'owner' : IDL.Principal,
    'systemId' : IDL.Text,
    'apiEndpoint' : IDL.Text,
    'brand' : IDL.Text,
    'systemType' : IDL.Text,
  });
  const ValueProposition = IDL.Record({
    'id' : IDL.Text,
    'title' : IDL.Text,
    'createdAt' : Time,
    'description' : IDL.Text,
    'targetAudience' : IDL.Text,
    'updatedAt' : Time,
    'benefits' : IDL.Vec(IDL.Text),
  });
  const WeatherData = IDL.Record({
    'temperature' : IDL.Float64,
    'timestamp' : Time,
    'location' : IDL.Text,
    'condition' : IDL.Text,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const ShoppingItem = IDL.Record({
    'productName' : IDL.Text,
    'currency' : IDL.Text,
    'quantity' : IDL.Nat,
    'priceInCents' : IDL.Nat,
    'productDescription' : IDL.Text,
  });
  const DeviceHealth = IDL.Record({
    'tagId' : IDL.Text,
    'userId' : IDL.Principal,
    'quality' : DeviceQuality,
    'lastValue' : IDL.Opt(IDL.Text),
    'deviceId' : IDL.Text,
    'lastChecked' : Time,
    'lastValueTimestamp' : Time,
  });
  const SystemConfigPublic = IDL.Record({
    'region' : IDL.Text,
    'systemId' : IDL.Text,
    'apiEndpoint' : IDL.Text,
    'brand' : IDL.Text,
    'systemType' : IDL.Text,
  });
  const UserProfile = IDL.Record({
    'preferredLanguage' : IDL.Text,
    'name' : IDL.Text,
  });
  const NercCipStandard = IDL.Record({
    'title' : IDL.Text,
    'description' : IDL.Text,
    'standardId' : IDL.Text,
    'purpose' : IDL.Text,
  });
  const ComplianceSubsection = IDL.Record({
    'title' : IDL.Text,
    'content' : IDL.Text,
  });
  const ComplianceSection = IDL.Record({
    'title' : IDL.Text,
    'content' : IDL.Text,
    'subsections' : IDL.Vec(ComplianceSubsection),
  });
  const ComplianceReportData = IDL.Record({
    'title' : IDL.Text,
    'quickReferenceTable' : IDL.Text,
    'nercCipStandards' : IDL.Vec(NercCipStandard),
    'generatedAt' : Time,
    'legalDeclaration' : IDL.Text,
    'sections' : IDL.Vec(ComplianceSection),
    'nistCsfResponsibilities' : IDL.Text,
  });
  const CanisterStatus = IDL.Variant({
    'failing' : IDL.Null,
    'offline' : IDL.Null,
    'unknown' : IDL.Null,
    'online' : IDL.Null,
  });
  const CanisterInfo = IDL.Record({
    'status' : CanisterStatus,
    'name' : IDL.Text,
    'errorMessage' : IDL.Opt(IDL.Text),
    'lastChecked' : Time,
    'canisterId' : IDL.Text,
  });
  const DomainStatus = IDL.Record({
    'isAccessible' : IDL.Bool,
    'sslValid' : IDL.Bool,
    'lastChecked' : Time,
    'primaryDomain' : IDL.Text,
  });
  const DeploymentStatus = IDL.Record({
    'canisters' : IDL.Vec(CanisterInfo),
    'timestamp' : Time,
    'overallStatus' : IDL.Text,
    'domainStatus' : DomainStatus,
  });
  const DomainVariant = IDL.Record({
    'domain' : IDL.Text,
    'isAvailable' : IDL.Bool,
    'registrar' : IDL.Text,
    'lastChecked' : Time,
    'priceUsd' : IDL.Float64,
  });
  const DomainPortfolio = IDL.Record({
    'recommendations' : IDL.Text,
    'strategy' : IDL.Text,
    'lastUpdated' : Time,
    'variants' : IDL.Vec(DomainVariant),
  });
  const MaintenanceConfig = IDL.Record({
    'alertEscalationThreshold' : IDL.Nat,
    'createdAt' : Time,
    'autoRepairThreshold' : IDL.Nat,
    'maxRetries' : IDL.Nat,
    'isActive' : IDL.Bool,
    'updatedAt' : Time,
  });
  const ServiceStatus = IDL.Variant({
    'unhealthy' : IDL.Null,
    'healthy' : IDL.Null,
    'degraded' : IDL.Null,
    'unknown' : IDL.Null,
  });
  const SystemHealth = IDL.Record({
    'activeProcesses' : IDL.Vec(IDL.Text),
    'dataSyncStatus' : ServiceStatus,
    'deviceIntegrationStatus' : ServiceStatus,
    'backendStatus' : ServiceStatus,
    'networkStatus' : ServiceStatus,
    'uptime' : IDL.Float64,
    'performanceMetrics' : IDL.Text,
    'overallStatus' : ServiceStatus,
  });
  const MaintenanceDashboard = IDL.Record({
    'optimizationSuggestions' : IDL.Vec(IDL.Text),
    'learningUpdates' : IDL.Vec(LearningUpdate),
    'config' : MaintenanceConfig,
    'systemHealth' : SystemHealth,
    'recentEvents' : IDL.Vec(MaintenanceEvent),
  });
  const StripeSessionStatus = IDL.Variant({
    'completed' : IDL.Record({
      'userPrincipal' : IDL.Opt(IDL.Text),
      'response' : IDL.Text,
    }),
    'failed' : IDL.Record({ 'error' : IDL.Text }),
  });
  const StripeConfiguration = IDL.Record({
    'allowedCountries' : IDL.Vec(IDL.Text),
    'secretKey' : IDL.Text,
  });
  const http_header = IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text });
  const http_request_result = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  const TransformationInput = IDL.Record({
    'context' : IDL.Vec(IDL.Nat8),
    'response' : http_request_result,
  });
  const TransformationOutput = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    'addAlarmConfig' : IDL.Func([AlarmConfig], [], []),
    'addCaseStudy' : IDL.Func([CaseStudy], [], []),
    'addDNSSyncResult' : IDL.Func([DNSSyncResult], [], []),
    'addDiagnosticEvent' : IDL.Func([DiagnosticEvent], [], []),
    'addDiagnosticFeedback' : IDL.Func([DiagnosticFeedback], [], []),
    'addEVOAuthConfig' : IDL.Func([EVOAuthConfig], [], []),
    'addEVTelemetry' : IDL.Func([EVTelemetry], [], []),
    'addEnergyData' : IDL.Func([EnergyData], [], []),
    'addEnergySummary' : IDL.Func([EnergySummary], [], []),
    'addErrorCode' : IDL.Func([ErrorCode], [], []),
    'addICPGatewayConfig' : IDL.Func([ICPGatewayConfig], [], []),
    'addLearningUpdate' : IDL.Func([LearningUpdate], [], []),
    'addMaintenanceEvent' : IDL.Func([MaintenanceEvent], [], []),
    'addManufacturerSupport' : IDL.Func([ManufacturerSupport], [], []),
    'addMotivationalMessage' : IDL.Func([MotivationalMessage], [], []),
    'addPredictiveModel' : IDL.Func([PredictiveModel], [], []),
    'addPricingTier' : IDL.Func([PricingTier], [], []),
    'addRecommendation' : IDL.Func([Recommendation], [], []),
    'addRegionalPricingModel' : IDL.Func([RegionalPricingModel], [], []),
    'addScadaProtocol' : IDL.Func([ScadaProtocolSupport], [], []),
    'addScheduledUpdate' : IDL.Func([ScheduledUpdate], [], []),
    'addSupportBoundary' : IDL.Func([SupportBoundary], [], []),
    'addSupportContract' : IDL.Func([SupportContract], [], []),
    'addSupportedDevice' : IDL.Func([SupportedDevice], [], []),
    'addSystemConfig' : IDL.Func([SystemConfig], [], []),
    'addValueProposition' : IDL.Func([ValueProposition], [], []),
    'addWeatherData' : IDL.Func([WeatherData], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createCheckoutSession' : IDL.Func(
        [IDL.Vec(ShoppingItem), IDL.Text, IDL.Text],
        [IDL.Text],
        [],
      ),
    'deleteAlarmConfig' : IDL.Func([IDL.Text], [], []),
    'deleteEnergyData' : IDL.Func([IDL.Text, Time], [], []),
    'deletePredictiveModel' : IDL.Func([IDL.Text], [], []),
    'deleteRecommendation' : IDL.Func([IDL.Text], [], []),
    'deleteRegionalPricingModel' : IDL.Func([IDL.Text], [], []),
    'deleteScheduledUpdate' : IDL.Func([IDL.Text], [], []),
    'deleteSupportedDevice' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'deleteSystemConfig' : IDL.Func([IDL.Text], [], []),
    'getAlarmConfig' : IDL.Func([IDL.Text], [IDL.Opt(AlarmConfig)], ['query']),
    'getAllAlarmConfigs' : IDL.Func([], [IDL.Vec(AlarmConfig)], ['query']),
    'getAllCaseStudies' : IDL.Func([], [IDL.Vec(CaseStudy)], ['query']),
    'getAllDeviceHealth' : IDL.Func([], [IDL.Vec(DeviceHealth)], ['query']),
    'getAllDiagnosticEvents' : IDL.Func(
        [],
        [IDL.Vec(DiagnosticEvent)],
        ['query'],
      ),
    'getAllEnergyData' : IDL.Func([], [IDL.Vec(EnergyData)], ['query']),
    'getAllErrorCodes' : IDL.Func([], [IDL.Vec(ErrorCode)], ['query']),
    'getAllICPGatewayConfigs' : IDL.Func(
        [],
        [IDL.Vec(ICPGatewayConfig)],
        ['query'],
      ),
    'getAllManufacturerSupport' : IDL.Func(
        [],
        [IDL.Vec(ManufacturerSupport)],
        ['query'],
      ),
    'getAllMotivationalMessages' : IDL.Func(
        [],
        [IDL.Vec(MotivationalMessage)],
        ['query'],
      ),
    'getAllPricingTiers' : IDL.Func([], [IDL.Vec(PricingTier)], ['query']),
    'getAllRegionalPricingModels' : IDL.Func(
        [],
        [IDL.Vec(RegionalPricingModel)],
        ['query'],
      ),
    'getAllScadaProtocols' : IDL.Func(
        [],
        [IDL.Vec(ScadaProtocolSupport)],
        ['query'],
      ),
    'getAllScheduledUpdates' : IDL.Func(
        [],
        [IDL.Vec(ScheduledUpdate)],
        ['query'],
      ),
    'getAllSupportBoundaries' : IDL.Func(
        [],
        [IDL.Vec(SupportBoundary)],
        ['query'],
      ),
    'getAllSupportedDevices' : IDL.Func(
        [],
        [IDL.Vec(SupportedDevice)],
        ['query'],
      ),
    'getAllSystemConfigs' : IDL.Func(
        [],
        [IDL.Vec(SystemConfigPublic)],
        ['query'],
      ),
    'getAllSystemConfigsFull' : IDL.Func(
        [],
        [IDL.Vec(SystemConfig)],
        ['query'],
      ),
    'getAllValuePropositions' : IDL.Func(
        [],
        [IDL.Vec(ValueProposition)],
        ['query'],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getComplianceReportData' : IDL.Func(
        [],
        [IDL.Opt(ComplianceReportData)],
        ['query'],
      ),
    'getDNSSyncHistory' : IDL.Func([], [IDL.Vec(DNSSyncResult)], ['query']),
    'getDeploymentStatus' : IDL.Func(
        [],
        [IDL.Opt(DeploymentStatus)],
        ['query'],
      ),
    'getDeviceHealth' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(DeviceHealth)],
        ['query'],
      ),
    'getDiagnosticEvent' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(DiagnosticEvent)],
        ['query'],
      ),
    'getDiagnosticFeedback' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(DiagnosticFeedback)],
        ['query'],
      ),
    'getDomainPortfolio' : IDL.Func([], [IDL.Opt(DomainPortfolio)], ['query']),
    'getEVOAuthConfig' : IDL.Func(
        [IDL.Principal, EVProvider],
        [IDL.Opt(EVOAuthConfig)],
        ['query'],
      ),
    'getEVTelemetry' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(EVTelemetry)],
        ['query'],
      ),
    'getEnergyData' : IDL.Func([IDL.Text], [IDL.Vec(EnergyData)], ['query']),
    'getEnergySummary' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(EnergySummary)],
        ['query'],
      ),
    'getErrorCode' : IDL.Func(
        [IDL.Text, IDL.Text],
        [IDL.Opt(ErrorCode)],
        ['query'],
      ),
    'getMaintenanceDashboard' : IDL.Func([], [MaintenanceDashboard], ['query']),
    'getPredictiveModel' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(PredictiveModel)],
        ['query'],
      ),
    'getRecommendations' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(Recommendation)],
        ['query'],
      ),
    'getRegionalPricingModel' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(RegionalPricingModel)],
        ['query'],
      ),
    'getScheduledUpdate' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(ScheduledUpdate)],
        ['query'],
      ),
    'getStripeSessionStatus' : IDL.Func([IDL.Text], [StripeSessionStatus], []),
    'getSupportContract' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(SupportContract)],
        ['query'],
      ),
    'getSystemConfig' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(SystemConfigPublic)],
        ['query'],
      ),
    'getSystemConfigFull' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(SystemConfig)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getWeatherData' : IDL.Func([IDL.Text], [IDL.Opt(WeatherData)], ['query']),
    'initializeAccessControl' : IDL.Func([], [], []),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isStripeConfigured' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'setComplianceReportData' : IDL.Func([ComplianceReportData], [], []),
    'setDeploymentStatus' : IDL.Func([DeploymentStatus], [], []),
    'setDomainPortfolio' : IDL.Func([DomainPortfolio], [], []),
    'setStripeConfiguration' : IDL.Func([StripeConfiguration], [], []),
    'transform' : IDL.Func(
        [TransformationInput],
        [TransformationOutput],
        ['query'],
      ),
    'updateAlarmConfig' : IDL.Func([AlarmConfig], [], []),
    'updateDeviceHealth' : IDL.Func([DeviceHealth], [], []),
    'updateMaintenanceConfig' : IDL.Func([MaintenanceConfig], [], []),
    'updatePricingTier' : IDL.Func([PricingTier], [], []),
    'updateSystemConfig' : IDL.Func([SystemConfig], [], []),
    'updateSystemHealth' : IDL.Func([SystemHealth], [], []),
  });
};

export const init = ({ IDL }) => { return []; };