/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AlarmConfig {
  'alertBeep' : string,
  'ringTone' : string,
  'alarmId' : string,
  'userId' : Principal,
  'createdAt' : Time,
  'wakeUpTime' : Time,
  'isActive' : boolean,
  'language' : string,
  'updatedAt' : Time,
}
export interface CanisterInfo {
  'status' : CanisterStatus,
  'name' : string,
  'errorMessage' : [] | [string],
  'lastChecked' : Time,
  'canisterId' : string,
}
export type CanisterStatus = { 'failing' : null } |
  { 'offline' : null } |
  { 'unknown' : null } |
  { 'online' : null };
export interface CaseStudy {
  'id' : string,
  'region' : string,
  'protocolsUsed' : Array<string>,
  'title' : string,
  'createdAt' : Time,
  'description' : string,
  'reliability' : number,
  'updatedAt' : Time,
  'energySavings' : number,
}
export interface ComplianceReportData {
  'title' : string,
  'quickReferenceTable' : string,
  'nercCipStandards' : Array<NercCipStandard>,
  'generatedAt' : Time,
  'legalDeclaration' : string,
  'sections' : Array<ComplianceSection>,
  'nistCsfResponsibilities' : string,
}
export interface ComplianceSection {
  'title' : string,
  'content' : string,
  'subsections' : Array<ComplianceSubsection>,
}
export interface ComplianceSubsection { 'title' : string, 'content' : string }
export interface DNSSyncResult {
  'domain' : string,
  'message' : string,
  'timestamp' : Time,
  'success' : boolean,
}
export interface DeploymentStatus {
  'canisters' : Array<CanisterInfo>,
  'timestamp' : Time,
  'overallStatus' : string,
  'domainStatus' : DomainStatus,
}
export interface DeviceHealth {
  'tagId' : string,
  'userId' : Principal,
  'quality' : DeviceQuality,
  'lastValue' : [] | [string],
  'deviceId' : string,
  'lastChecked' : Time,
  'lastValueTimestamp' : Time,
}
export type DeviceQuality = { 'bad' : null } |
  { 'good' : null } |
  { 'uncertain' : null };
export interface DiagnosticCheckResult {
  'status' : string,
  'message' : string,
  'checkType' : string,
  'timestamp' : Time,
}
export interface DiagnosticEvent {
  'id' : string,
  'status' : string,
  'tagId' : string,
  'manufacturerReferralUrl' : [] | [string],
  'userId' : Principal,
  'quality' : DeviceQuality,
  'errorCode' : [] | [string],
  'diagnosis' : string,
  'progressPercent' : bigint,
  'deviceId' : string,
  'timestamp' : Time,
  'suggestedActions' : Array<string>,
  'checks' : Array<DiagnosticCheckResult>,
}
export interface DiagnosticFeedback {
  'id' : string,
  'userId' : Principal,
  'comment' : [] | [string],
  'wasHelpful' : boolean,
  'diagnosticEventId' : string,
  'timestamp' : Time,
}
export interface DomainPortfolio {
  'recommendations' : string,
  'strategy' : string,
  'lastUpdated' : Time,
  'variants' : Array<DomainVariant>,
}
export interface DomainStatus {
  'isAccessible' : boolean,
  'sslValid' : boolean,
  'lastChecked' : Time,
  'primaryDomain' : string,
}
export interface DomainVariant {
  'domain' : string,
  'isAvailable' : boolean,
  'registrar' : string,
  'lastChecked' : Time,
  'priceUsd' : number,
}
export interface EVOAuthConfig {
  'expiresAt' : Time,
  'provider' : EVProvider,
  'refreshToken' : string,
  'userId' : Principal,
  'createdAt' : Time,
  'updatedAt' : Time,
  'accessToken' : string,
}
export type EVProvider = { 'ford' : null } |
  { 'rivian' : null };
export interface EVTelemetry {
  'provider' : EVProvider,
  'batteryPercent' : number,
  'userId' : Principal,
  'chargingStatus' : string,
  'timestamp' : Time,
  'rangeKm' : number,
  'vehicleId' : string,
}
export interface EnergyData {
  'temperature' : number,
  'systemId' : string,
  'timestamp' : Time,
  'energyConsumption' : number,
  'location' : string,
  'timeZone' : string,
}
export interface EnergySummary {
  'totalConsumption' : number,
  'systemId' : string,
  'peakUsage' : number,
  'timestamp' : Time,
}
export interface ErrorCode {
  'manufacturer' : string,
  'code' : string,
  'createdAt' : Time,
  'supportUrl' : string,
  'description' : string,
  'isActive' : boolean,
  'updatedAt' : Time,
  'plainEnglishMessage' : string,
}
export interface ICPGatewayConfig {
  'domain' : string,
  'errorMessage' : [] | [string],
  'tlsCertificateValid' : boolean,
  'lastSyncTimestamp' : Time,
  'isRegistered' : boolean,
  'canisterId' : string,
}
export interface LearningUpdate {
  'id' : string,
  'impact' : string,
  'issuePattern' : string,
  'deviceCorrelation' : string,
  'timestamp' : Time,
  'optimizationSuggestion' : string,
}
export interface MaintenanceConfig {
  'alertEscalationThreshold' : bigint,
  'createdAt' : Time,
  'autoRepairThreshold' : bigint,
  'maxRetries' : bigint,
  'isActive' : boolean,
  'updatedAt' : Time,
}
export interface MaintenanceDashboard {
  'optimizationSuggestions' : Array<string>,
  'learningUpdates' : Array<LearningUpdate>,
  'config' : MaintenanceConfig,
  'systemHealth' : SystemHealth,
  'recentEvents' : Array<MaintenanceEvent>,
}
export interface MaintenanceEvent {
  'id' : string,
  'service' : string,
  'status' : string,
  'issueType' : string,
  'resolution' : string,
  'retryCount' : bigint,
  'timeToResolution' : bigint,
  'timestamp' : Time,
  'rootCause' : string,
}
export interface ManufacturerSupport {
  'id' : string,
  'name' : string,
  'createdAt' : Time,
  'supportUrl' : string,
  'description' : string,
  'isActive' : boolean,
  'updatedAt' : Time,
  'logoUrl' : string,
}
export interface MotivationalMessage {
  'content' : string,
  'messageId' : string,
  'language' : string,
  'timestamp' : Time,
}
export interface NercCipStandard {
  'title' : string,
  'description' : string,
  'standardId' : string,
  'purpose' : string,
}
export interface PredictiveModel {
  'lastUpdated' : Time,
  'systemId' : string,
  'modelData' : string,
  'modelId' : string,
  'timeZone' : string,
}
export interface PricingTier {
  'id' : string,
  'features' : Array<string>,
  'tierType' : string,
  'name' : string,
  'createdAt' : Time,
  'description' : string,
  'isActive' : boolean,
  'updatedAt' : Time,
  'currency' : string,
  'price' : number,
}
export interface Recommendation {
  'id' : string,
  'region' : string,
  'systemId' : string,
  'language' : string,
  'message' : string,
  'timestamp' : Time,
}
export interface RegionalPricingModel {
  'region' : string,
  'peakHours' : Array<string>,
  'pricePerKWh' : number,
  'currency' : string,
}
export interface ScadaProtocolSupport {
  'id' : string,
  'protocol' : string,
  'createdAt' : Time,
  'tier' : string,
  'description' : string,
  'isActive' : boolean,
  'supportedDevices' : Array<string>,
  'updatedAt' : Time,
}
export interface ScheduledUpdate {
  'updateType' : string,
  'userId' : Principal,
  'createdAt' : Time,
  'isActive' : boolean,
  'updateId' : string,
  'updatedAt' : Time,
  'scheduleTime' : Time,
  'frequency' : string,
}
export type ServiceStatus = { 'unhealthy' : null } |
  { 'healthy' : null } |
  { 'degraded' : null } |
  { 'unknown' : null };
export interface ShoppingItem {
  'productName' : string,
  'currency' : string,
  'quantity' : bigint,
  'priceInCents' : bigint,
  'productDescription' : string,
}
export interface StripeConfiguration {
  'allowedCountries' : Array<string>,
  'secretKey' : string,
}
export type StripeSessionStatus = {
    'completed' : { 'userPrincipal' : [] | [string], 'response' : string }
  } |
  { 'failed' : { 'error' : string } };
export interface SupportBoundary {
  'id' : string,
  'createdAt' : Time,
  'description' : string,
  'isActive' : boolean,
  'updatedAt' : Time,
}
export interface SupportContract {
  'expiresAt' : Time,
  'userId' : Principal,
  'tier' : string,
  'isActive' : boolean,
}
export interface SupportedDevice {
  'region' : string,
  'model' : string,
  'brand' : string,
  'systemType' : string,
}
export interface SystemConfig {
  'region' : string,
  'authToken' : string,
  'owner' : Principal,
  'systemId' : string,
  'apiEndpoint' : string,
  'brand' : string,
  'systemType' : string,
}
export interface SystemConfigPublic {
  'region' : string,
  'systemId' : string,
  'apiEndpoint' : string,
  'brand' : string,
  'systemType' : string,
}
export interface SystemHealth {
  'activeProcesses' : Array<string>,
  'dataSyncStatus' : ServiceStatus,
  'deviceIntegrationStatus' : ServiceStatus,
  'backendStatus' : ServiceStatus,
  'networkStatus' : ServiceStatus,
  'uptime' : number,
  'performanceMetrics' : string,
  'overallStatus' : ServiceStatus,
}
export type Time = bigint;
export interface TransformationInput {
  'context' : Uint8Array,
  'response' : http_request_result,
}
export interface TransformationOutput {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface UserProfile { 'preferredLanguage' : string, 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface ValueProposition {
  'id' : string,
  'title' : string,
  'createdAt' : Time,
  'description' : string,
  'targetAudience' : string,
  'updatedAt' : Time,
  'benefits' : Array<string>,
}
export interface WeatherData {
  'temperature' : number,
  'timestamp' : Time,
  'location' : string,
  'condition' : string,
}
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface http_header { 'value' : string, 'name' : string }
export interface http_request_result {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  'addAlarmConfig' : ActorMethod<[AlarmConfig], undefined>,
  'addCaseStudy' : ActorMethod<[CaseStudy], undefined>,
  'addDNSSyncResult' : ActorMethod<[DNSSyncResult], undefined>,
  'addDiagnosticEvent' : ActorMethod<[DiagnosticEvent], undefined>,
  'addDiagnosticFeedback' : ActorMethod<[DiagnosticFeedback], undefined>,
  'addEVOAuthConfig' : ActorMethod<[EVOAuthConfig], undefined>,
  'addEVTelemetry' : ActorMethod<[EVTelemetry], undefined>,
  'addEnergyData' : ActorMethod<[EnergyData], undefined>,
  'addEnergySummary' : ActorMethod<[EnergySummary], undefined>,
  'addErrorCode' : ActorMethod<[ErrorCode], undefined>,
  'addICPGatewayConfig' : ActorMethod<[ICPGatewayConfig], undefined>,
  'addLearningUpdate' : ActorMethod<[LearningUpdate], undefined>,
  'addMaintenanceEvent' : ActorMethod<[MaintenanceEvent], undefined>,
  'addManufacturerSupport' : ActorMethod<[ManufacturerSupport], undefined>,
  'addMotivationalMessage' : ActorMethod<[MotivationalMessage], undefined>,
  'addPredictiveModel' : ActorMethod<[PredictiveModel], undefined>,
  'addPricingTier' : ActorMethod<[PricingTier], undefined>,
  'addRecommendation' : ActorMethod<[Recommendation], undefined>,
  'addRegionalPricingModel' : ActorMethod<[RegionalPricingModel], undefined>,
  'addScadaProtocol' : ActorMethod<[ScadaProtocolSupport], undefined>,
  'addScheduledUpdate' : ActorMethod<[ScheduledUpdate], undefined>,
  'addSupportBoundary' : ActorMethod<[SupportBoundary], undefined>,
  'addSupportContract' : ActorMethod<[SupportContract], undefined>,
  'addSupportedDevice' : ActorMethod<[SupportedDevice], undefined>,
  'addSystemConfig' : ActorMethod<[SystemConfig], undefined>,
  'addValueProposition' : ActorMethod<[ValueProposition], undefined>,
  'addWeatherData' : ActorMethod<[WeatherData], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createCheckoutSession' : ActorMethod<
    [Array<ShoppingItem>, string, string],
    string
  >,
  'deleteAlarmConfig' : ActorMethod<[string], undefined>,
  'deleteEnergyData' : ActorMethod<[string, Time], undefined>,
  'deletePredictiveModel' : ActorMethod<[string], undefined>,
  'deleteRecommendation' : ActorMethod<[string], undefined>,
  'deleteRegionalPricingModel' : ActorMethod<[string], undefined>,
  'deleteScheduledUpdate' : ActorMethod<[string], undefined>,
  'deleteSupportedDevice' : ActorMethod<[string, string], undefined>,
  'deleteSystemConfig' : ActorMethod<[string], undefined>,
  'getAlarmConfig' : ActorMethod<[string], [] | [AlarmConfig]>,
  'getAllAlarmConfigs' : ActorMethod<[], Array<AlarmConfig>>,
  'getAllCaseStudies' : ActorMethod<[], Array<CaseStudy>>,
  'getAllDeviceHealth' : ActorMethod<[], Array<DeviceHealth>>,
  'getAllDiagnosticEvents' : ActorMethod<[], Array<DiagnosticEvent>>,
  'getAllEnergyData' : ActorMethod<[], Array<EnergyData>>,
  'getAllErrorCodes' : ActorMethod<[], Array<ErrorCode>>,
  'getAllICPGatewayConfigs' : ActorMethod<[], Array<ICPGatewayConfig>>,
  'getAllManufacturerSupport' : ActorMethod<[], Array<ManufacturerSupport>>,
  'getAllMotivationalMessages' : ActorMethod<[], Array<MotivationalMessage>>,
  'getAllPricingTiers' : ActorMethod<[], Array<PricingTier>>,
  'getAllRegionalPricingModels' : ActorMethod<[], Array<RegionalPricingModel>>,
  'getAllScadaProtocols' : ActorMethod<[], Array<ScadaProtocolSupport>>,
  'getAllScheduledUpdates' : ActorMethod<[], Array<ScheduledUpdate>>,
  'getAllSupportBoundaries' : ActorMethod<[], Array<SupportBoundary>>,
  'getAllSupportedDevices' : ActorMethod<[], Array<SupportedDevice>>,
  'getAllSystemConfigs' : ActorMethod<[], Array<SystemConfigPublic>>,
  'getAllSystemConfigsFull' : ActorMethod<[], Array<SystemConfig>>,
  'getAllValuePropositions' : ActorMethod<[], Array<ValueProposition>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getComplianceReportData' : ActorMethod<[], [] | [ComplianceReportData]>,
  'getDNSSyncHistory' : ActorMethod<[], Array<DNSSyncResult>>,
  'getDeploymentStatus' : ActorMethod<[], [] | [DeploymentStatus]>,
  'getDeviceHealth' : ActorMethod<[string], [] | [DeviceHealth]>,
  'getDiagnosticEvent' : ActorMethod<[string], [] | [DiagnosticEvent]>,
  'getDiagnosticFeedback' : ActorMethod<[string], Array<DiagnosticFeedback>>,
  'getDomainPortfolio' : ActorMethod<[], [] | [DomainPortfolio]>,
  'getEVOAuthConfig' : ActorMethod<
    [Principal, EVProvider],
    [] | [EVOAuthConfig]
  >,
  'getEVTelemetry' : ActorMethod<[Principal], Array<EVTelemetry>>,
  'getEnergyData' : ActorMethod<[string], Array<EnergyData>>,
  'getEnergySummary' : ActorMethod<[string], Array<EnergySummary>>,
  'getErrorCode' : ActorMethod<[string, string], [] | [ErrorCode]>,
  'getMaintenanceDashboard' : ActorMethod<[], MaintenanceDashboard>,
  'getPredictiveModel' : ActorMethod<[string], [] | [PredictiveModel]>,
  'getRecommendations' : ActorMethod<[string], Array<Recommendation>>,
  'getRegionalPricingModel' : ActorMethod<
    [string],
    [] | [RegionalPricingModel]
  >,
  'getScheduledUpdate' : ActorMethod<[string], [] | [ScheduledUpdate]>,
  'getStripeSessionStatus' : ActorMethod<[string], StripeSessionStatus>,
  'getSupportContract' : ActorMethod<[Principal], [] | [SupportContract]>,
  'getSystemConfig' : ActorMethod<[string], [] | [SystemConfigPublic]>,
  'getSystemConfigFull' : ActorMethod<[string], [] | [SystemConfig]>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getWeatherData' : ActorMethod<[string], [] | [WeatherData]>,
  'initializeAccessControl' : ActorMethod<[], undefined>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'isStripeConfigured' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'setComplianceReportData' : ActorMethod<[ComplianceReportData], undefined>,
  'setDeploymentStatus' : ActorMethod<[DeploymentStatus], undefined>,
  'setDomainPortfolio' : ActorMethod<[DomainPortfolio], undefined>,
  'setStripeConfiguration' : ActorMethod<[StripeConfiguration], undefined>,
  'transform' : ActorMethod<[TransformationInput], TransformationOutput>,
  'updateAlarmConfig' : ActorMethod<[AlarmConfig], undefined>,
  'updateDeviceHealth' : ActorMethod<[DeviceHealth], undefined>,
  'updateMaintenanceConfig' : ActorMethod<[MaintenanceConfig], undefined>,
  'updatePricingTier' : ActorMethod<[PricingTier], undefined>,
  'updateSystemConfig' : ActorMethod<[SystemConfig], undefined>,
  'updateSystemHealth' : ActorMethod<[SystemHealth], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];